### ISSUE TITLE
Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.

### ISSUE THREAD

**Issue by ghvillasboas** [CleverbotIO/ruby-cleverbot.io#7]
Since 1.2.2 (including 1.2.3), Cleverbot isn't working anymore and giving me the following error.
Any fix expected on the pipeline?

Thanks.

irb(main):004:0> bot.say('Why am I still talking to you?')
Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.
RuntimeError: Error: Bad Call to the API UNRECOGNIZED ERROR! PLEASE REPORT TO CLEVERBOT RUBY ISSUE TRACKER.
	from /Users/george/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cleverbot_io-1.2.3/lib/cleverbot.rb:62:in `try_throw'
	from /Users/george/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cleverbot_io-1.2.3/lib/cleverbot.rb:46:in `say'
	from (irb):4
	from /Users/george/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'

**Comment by elifoster** [comment]
Those are unrelated. 

`Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.` is an HTTPClient warning and doesn't actually error.

As for the "Bad Call" error, it seems like it's a cleverbot-wide issue. @dtesler is looking into it.

**Comment by ghvillasboas** [comment]
Thank you!
It indeed looks like a server side issue, not even on the TRY button on your website it seems to work.

![screen shot 2017-01-23 at 9 30 55 pm](https://cloud.githubusercontent.com/assets/2243183/22227616/527c2f16-e1b3-11e6-909f-fa20b64f56ff.png)

**Comment by elifoster** [comment]
From the Slack:

>david [4:07 PM] 
@ everyone minor downtime on API due to excess Algolia operations.  I suppose 3M API calls/day may have had something to do with that.  Working on a solution. (edited)
